(function(){
'use strict';
const KEY='btc-pine-scripts-v3';
const DEFAULT_CODE='indicator("5m 15m Levels")\nexactDrawings()';
let scripts=[], active=0, host, root;
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function defaults(){return [
 {name:'5m 15m Levels',code:DEFAULT_CODE,enabled:true},
 {name:'Pine Test EMA',code:'indicator("Pine Test EMA")\nfast = ta.ema(close, 20)\nslow = ta.ema(close, 50)\nplot(fast)\nplot(slow)',enabled:false}
]}
function loadSaved(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(Array.isArray(x)&&x.length)return x}catch(e){}return defaults()}
function saveSaved(){try{localStorage.setItem(KEY,JSON.stringify(scripts))}catch(e){}}
function css(){return `:host{all:initial}*{box-sizing:border-box}#p{position:fixed;top:12px;right:12px;width:540px;height:620px;z-index:2147483647;background:#111722;color:#d1d4dc;border:1px solid #465264;border-radius:7px;box-shadow:0 14px 50px rgba(0,0,0,.65);font:13px Arial,sans-serif;display:flex;flex-direction:column;overflow:hidden}#p.min{height:46px;width:260px}#p.min .body{display:none}.head{height:46px;min-height:46px;display:flex;align-items:center;justify-content:space-between;padding:0 10px 0 14px;background:#151c27;border-bottom:1px solid #303846;font-weight:bold;font-size:14px}.head-actions{display:flex;gap:6px}.btn{appearance:none!important;-webkit-appearance:none!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;visibility:visible!important;opacity:1!important;pointer-events:auto!important;background:#202b3a!important;color:#e6edf3!important;border:1px solid #536277!important;border-radius:4px!important;padding:7px 11px!important;min-height:30px!important;line-height:1!important;font:12px Arial,sans-serif!important;cursor:pointer!important}.btn:hover{background:#2b394d!important}.primary{border-color:#7dd3fc!important}.body{flex:1;min-height:0;display:flex;flex-direction:column}.toolbar{display:flex;gap:6px;padding:9px;border-bottom:1px solid #2a3441}.select{flex:1;min-width:0;background:#0d131c;color:#e6edf3;border:1px solid #536277;border-radius:4px;padding:8px;font:12px Arial}.list{display:flex;gap:6px;flex-wrap:wrap;padding:8px;border-bottom:1px solid #2a3441;max-height:80px;overflow:auto}.item{display:flex;align-items:center;gap:6px;background:#18212d;border:1px solid #3c4a5e;border-radius:4px;padding:5px 7px}.item.active{border-color:#7dd3fc}.item span{cursor:pointer;max-width:180px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.item input{width:15px;height:15px}.editor{flex:1;min-height:0;padding:9px}.code{width:100%;height:100%;resize:none;background:#0a0f16;color:#e6edf3;border:1px solid #3c4a5e;border-radius:5px;padding:12px;font:13px Consolas,Monaco,monospace;line-height:1.5;outline:none}.footer{display:flex;gap:6px;align-items:center;padding:9px;border-top:1px solid #2a3441}.status{margin-left:auto;color:#aeb8c6;white-space:nowrap}.toggle{position:fixed;top:12px;right:12px;z-index:2147483646;background:#111722;color:#e6edf3;border:1px solid #536277;border-radius:5px;padding:8px 12px;font:12px Arial;cursor:pointer;box-shadow:0 5px 18px rgba(0,0,0,.45)}.file{display:none}`}
function setStatus(t){const e=root&&root.getElementById('status');if(e)e.textContent=t}
function render(){if(!root)return;const sel=root.getElementById('sel');sel.innerHTML=scripts.map((s,i)=>`<option value="${i}">${esc(s.name)}</option>`).join('');sel.value=String(active);root.getElementById('code').value=scripts[active]?.code||'';const list=root.getElementById('list');list.innerHTML=scripts.map((s,i)=>`<div class="item ${i===active?'active':''}"><input type="checkbox" data-en="${i}" ${s.enabled!==false?'checked':''}><span data-pick="${i}">${esc(s.name)}</span></div>`).join('')}
function apply(){scripts[active].code=root.getElementById('code').value;saveSaved();const enabled=scripts.filter(s=>s.enabled!==false);if(window.PineSystem&&PineSystem.setScripts)PineSystem.setScripts(enabled.map(s=>s.code));setStatus(`Running ${enabled.length} enabled script(s)`)}
function add(){scripts.push({name:`New Indicator ${scripts.length+1}`,code:'indicator("New Indicator")\nplot(close)',enabled:true});active=scripts.length-1;saveSaved();render();setStatus('New script created')}
function save(){scripts[active].code=root.getElementById('code').value;const n=prompt('Script name',scripts[active].name);if(n&&n.trim())scripts[active].name=n.trim();saveSaved();render();setStatus('Saved locally')}
function remove(){if(scripts.length<=1){setStatus('At least one script must remain');return}scripts.splice(active,1);active=Math.max(0,active-1);saveSaved();render();apply()}
function loadFile(file){const r=new FileReader();r.onload=()=>{scripts.push({name:file.name.replace(/\.pine$/i,''),code:String(r.result),enabled:true});active=scripts.length-1;saveSaved();render();apply()};r.readAsText(file)}
function build(){if(document.getElementById('pine-panel-host'))return;scripts=loadSaved();host=document.createElement('div');host.id='pine-panel-host';host.style.cssText='position:fixed!important;inset:0!important;width:0!important;height:0!important;z-index:2147483647!important;pointer-events:none!important';document.documentElement.appendChild(host);root=host.attachShadow({mode:'open'});const style=document.createElement('style');style.textContent=css();root.appendChild(style);
const toggle=document.createElement('button');toggle.className='toggle';toggle.textContent='Pine';toggle.style.display='none';toggle.onclick=()=>{panel.style.display='flex';toggle.style.display='none'};root.appendChild(toggle);
const panel=document.createElement('div');panel.id='p';panel.innerHTML=`<div class="head"><span>Pine Indicators</span><div class="head-actions"><button class="btn" id="min">−</button><button class="btn" id="close">×</button></div></div><div class="body"><div class="toolbar"><select class="select" id="sel"></select><button class="btn" id="new">New</button><button class="btn" id="load">Load .pine</button><input class="file" id="file" type="file" accept=".pine,.txt,text/plain"></div><div class="list" id="list"></div><div class="editor"><textarea class="code" id="code" spellcheck="false"></textarea></div><div class="footer"><button class="btn primary" id="run">Run</button><button class="btn" id="save">Save</button><button class="btn" id="remove">Remove</button><button class="btn" id="runall">Run Enabled</button><span class="status" id="status">Ready</span></div></div>`;root.appendChild(panel);render();
root.getElementById('sel').onchange=e=>{scripts[active].code=root.getElementById('code').value;active=+e.target.value;render()};
root.getElementById('new').onclick=add;root.getElementById('save').onclick=save;root.getElementById('remove').onclick=remove;root.getElementById('run').onclick=()=>{scripts[active].enabled=true;apply()};root.getElementById('runall').onclick=apply;root.getElementById('load').onclick=()=>root.getElementById('file').click();root.getElementById('file').onchange=e=>{if(e.target.files[0])loadFile(e.target.files[0]);e.target.value=''};root.getElementById('min').onclick=()=>panel.classList.toggle('min');root.getElementById('close').onclick=()=>{panel.style.display='none';toggle.style.display='block'};root.getElementById('list').onclick=e=>{const en=e.target.dataset.en,pick=e.target.dataset.pick;if(en!==undefined){scripts[+en].enabled=e.target.checked;saveSaved();apply()}if(pick!==undefined){scripts[active].code=root.getElementById('code').value;active=+pick;render()}};
setTimeout(()=>{if(window.PineSystem&&PineSystem.setScripts){PineSystem.setScripts(scripts.filter(s=>s.enabled!==false).map(s=>s.code));setStatus(`Loaded ${scripts.filter(s=>s.enabled!==false).length} enabled script(s)`)}} ,1800)}
window.PinePanel={init:build};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();setTimeout(build,1000);setTimeout(build,3000);})();
