(function(){
'use strict';
const KEY='btc-pine-scripts-v2';
const DEFAULT_NAME='5m 15m Levels';
const DEFAULT_CODE='indicator("5m 15m Levels")\nexactDrawings()';
let scripts=[]; let active=0;
function defaults(){return [{name:DEFAULT_NAME,code:DEFAULT_CODE,enabled:true}]}
function loadSaved(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(Array.isArray(x)&&x.length)return x}catch(e){}return defaults()}
function saveSaved(){try{localStorage.setItem(KEY,JSON.stringify(scripts))}catch(e){}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function css(){if(document.getElementById('pine-panel-css'))return;const st=document.createElement('style');st.id='pine-panel-css';st.textContent=`#pine-panel{position:fixed!important;top:12px!important;right:12px!important;width:430px!important;height:570px!important;max-width:calc(100vw - 24px)!important;z-index:2147483647!important;pointer-events:auto!important;background:#111722;border:1px solid #3a4555;border-radius:7px;box-shadow:0 12px 40px rgba(0,0,0,.55);color:#d1d4dc;font:12px Arial,sans-serif;display:flex;flex-direction:column}#pine-panel.hidden{display:none!important}#pine-panel.min{height:auto;width:250px}#pine-panel .ph{height:40px;flex:0 0 40px;display:flex;align-items:center;justify-content:space-between;padding:0 10px;border-bottom:1px solid #303846;font-weight:600;background:#151c27;border-radius:7px 7px 0 0}#pine-panel .actions{display:flex;gap:5px}#pine-panel button{display:inline-block!important;visibility:visible!important;opacity:1!important;pointer-events:auto!important;background:#1d2633;color:#d1d4dc;border:1px solid #3a4555;border-radius:4px;padding:6px 9px;cursor:pointer;font-size:11px}#pine-panel button:hover{background:#293547}#pine-panel .body{display:flex;flex:1;min-height:0;flex-direction:column}#pine-panel .bar{display:flex;gap:5px;padding:7px;border-bottom:1px solid #252e3a;align-items:center}#pine-panel select{background:#0d131c;color:#d1d4dc;border:1px solid #3a4555;border-radius:4px;padding:6px;font-size:11px;min-width:145px;flex:1}#pine-script-list{display:flex;gap:5px;flex-wrap:wrap;padding:7px;border-bottom:1px solid #252e3a;max-height:76px;overflow:auto}.ps-item{display:flex;align-items:center;gap:4px;background:#18212d;border:1px solid #344052;border-radius:4px;padding:4px 6px}.ps-item input{accent-color:#7dd3fc}.ps-item span{cursor:pointer;max-width:145px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ps-item.active{border-color:#7dd3fc}.editor{flex:1;min-height:0;padding:7px}.editor textarea{width:100%;height:100%;box-sizing:border-box;resize:none;background:#0b1017;color:#e6edf3;border:1px solid #303b4a;border-radius:4px;padding:10px;font:12px Consolas,monospace;line-height:1.5;outline:none}.footer{display:flex;gap:5px;padding:7px;border-top:1px solid #252e3a;flex-wrap:wrap}.status{margin-left:auto;opacity:.8;align-self:center;white-space:nowrap}.pine-toggle{position:fixed!important;top:12px!important;right:12px!important;z-index:2147483646!important;display:block!important;visibility:visible!important;pointer-events:auto!important;background:#111722;color:#d1d4dc;border:1px solid #3a4555;border-radius:5px;padding:7px 11px;cursor:pointer;font:12px Arial,sans-serif;box-shadow:0 5px 18px rgba(0,0,0,.35)}.hidden{display:none!important}`;document.head.appendChild(st)}
function setStatus(t){const e=document.getElementById('pine-status');if(e)e.textContent=t}
function render(){const p=document.getElementById('pine-panel');if(!p)return;const sel=p.querySelector('#pine-select');sel.innerHTML=scripts.map((x,i)=>`<option value="${i}">${esc(x.name)}</option>`).join('');sel.value=String(active);p.querySelector('#pine-script').value=scripts[active]?.code||'';const list=p.querySelector('#pine-script-list');list.innerHTML=scripts.map((x,i)=>`<div class="ps-item ${i===active?'active':''}"><input type="checkbox" data-en="${i}" ${x.enabled!==false?'checked':''}><span data-pick="${i}">${esc(x.name)}</span></div>`).join('')}
function currentCode(){return document.getElementById('pine-script')?.value||''}
function apply(){scripts[active].code=currentCode();saveSaved();window.PineSystem.setScripts(scripts.filter(x=>x.enabled!==false).map(x=>x.code));setStatus('Running '+scripts.filter(x=>x.enabled!==false).length+' enabled script(s)')}
function add(){scripts.push({name:'New Indicator '+(scripts.length+1),code:'indicator("New Indicator")\nplot(close)',enabled:true});active=scripts.length-1;saveSaved();render();setStatus('New script created')}
function save(){scripts[active].code=currentCode();const n=prompt('Script name',scripts[active].name);if(n&&n.trim())scripts[active].name=n.trim();saveSaved();render();setStatus('Saved locally')}
function remove(){if(scripts.length<=1){setStatus('At least one script must remain');return}scripts.splice(active,1);active=Math.max(0,active-1);saveSaved();render();apply()}
function loadFile(file){const r=new FileReader();r.onload=()=>{scripts.push({name:file.name.replace(/\.pine$/i,''),code:String(r.result),enabled:true});active=scripts.length-1;saveSaved();render();apply()};r.readAsText(file)}
function build(){if(document.getElementById('pine-panel'))return;css();scripts=loadSaved();const toggle=document.createElement('button');toggle.id='pine-reopen';toggle.className='pine-toggle';toggle.textContent='Pine';toggle.title='Open Pine Indicators';toggle.style.display='none';(document.documentElement||document.body).appendChild(toggle);const p=document.createElement('div');p.id='pine-panel';p.style.setProperty('display','flex','important');p.style.setProperty('visibility','visible','important');p.innerHTML=`<div class="ph"><span>Pine Indicators</span><div class="actions"><button id="pine-min" title="Minimize">−</button><button id="pine-close" title="Hide panel">×</button></div></div><div class="body"><div class="bar"><select id="pine-select" title="Saved scripts"></select><button id="pine-add">New</button><button id="pine-load">Load .pine</button><input id="pine-file" class="hidden" type="file" accept=".pine,.txt,text/plain"></div><div id="pine-script-list"></div><div class="editor"><textarea id="pine-script" spellcheck="false"></textarea></div><div class="footer"><button id="pine-run">Run</button><button id="pine-save">Save</button><button id="pine-remove">Remove</button><button id="pine-runall">Run Enabled</button><span class="status" id="pine-status">Ready</span></div></div>`;(document.documentElement||document.body).appendChild(p);render();
 p.querySelector('#pine-select').onchange=e=>{scripts[active].code=currentCode();active=+e.target.value;render()};p.querySelector('#pine-add').onclick=add;p.querySelector('#pine-save').onclick=save;p.querySelector('#pine-remove').onclick=remove;p.querySelector('#pine-run').onclick=()=>{scripts[active].enabled=true;apply()};p.querySelector('#pine-runall').onclick=apply;p.querySelector('#pine-load').onclick=()=>p.querySelector('#pine-file').click();p.querySelector('#pine-file').onchange=e=>{if(e.target.files[0])loadFile(e.target.files[0]);e.target.value=''};p.querySelector('#pine-min').onclick=()=>p.classList.toggle('min');p.querySelector('#pine-close').onclick=()=>{p.classList.add('hidden');toggle.style.display='block'};toggle.onclick=()=>{p.classList.remove('hidden');toggle.style.display='none'};p.querySelector('#pine-script-list').onclick=e=>{const en=e.target.dataset.en,pick=e.target.dataset.pick;if(en!==undefined){scripts[+en].enabled=e.target.checked;saveSaved();apply()}if(pick!==undefined){scripts[active].code=currentCode();active=+pick;render()}};
 setTimeout(()=>{window.PineSystem.setScripts(scripts.filter(x=>x.enabled!==false).map(x=>x.code));setStatus('Loaded '+scripts.filter(x=>x.enabled!==false).length+' enabled script(s)')},1500)}
window.PinePanel={init:build};
setTimeout(build, 500);
setTimeout(build, 2000);
setTimeout(build, 5000);
})();
